services:
  db_service:
    image: postgres:17.5
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=db-password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - dc_managed_db_volume:/var/lib/postgresql/data
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8080:8000"
    volumes:
      - ./backend/src:/app
    env_file:
      - .env.sample
    depends_on:
      - db_service
    develop:
      watch:
        - action: rebuild
          path: backend/requirements.txt
        - action: rebuild
          path: backend/Dockerfile
        - action: restart
          path: backend/src   # <- remove the leading slash
  # DATABASE_URL=postgresql+psycopg://dbuser:db-password@db_service:5432/mydb
  
    
  # static_html:
  #   build: 
  #     context: ./static_html
  #     dockerfile: static.DockerFile
  #   ports:
  #     - "8000:8000"
  #     - "3000:8000"
  #   command: python -m http.server 8000
  #   volumes:
  #     - ./static_html/src:/app
volumes:
  dc_managed_db_volume: