FROM python:3.13.4-slim-bullseye
WORKDIR /app

# Create python virtual environment
# isolate our python app and installs from system-level python
RUN python -m venv /opt/venv/
ENV PATH=/opt/venv/bin:$PATH

COPY ./src /app
COPY requirements.txt tmp/requirements.txt
RUN pip install  -r tmp/requirements.txt
# RUN echo "Hello, World!" > index.html
CMD [ "python", "-m", "http.server", "8000" ]